version: "3"
services:
  db:
    container_name: ers_db
    image: postgres
    # build:
    #   context: .
    #   dockerfile: docker/postgres/Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ers
      - POSTGRES_PASSWORD=r1e2w3q4
  app:
    container_name: ers_api
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: sh -c "/wait && /app/ers"
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:r1e2w3q4@db/ers
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
  nginx:
    container_name: ers_static
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    #   - app